# Generated by Django 4.2.5 on 2023-09-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('DOCTOR', 'Médecin'), ('PATIENT', 'Patient')], default='PATIENT', max_length=7),
        ),
    ]
