# Generated by Django 4.2.5 on 2023-09-20 08:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressEvaluationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_impact_du_stress_dans_votre_vie_actuelle', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDailyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('poids', models.FloatField(validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(300.0)])),
                ('tour_de_taille', models.IntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)])),
                ('frequence_cardiaque', models.IntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)])),
                ('tension_arterielle_matin_systolique', models.IntegerField(validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(200)])),
                ('tension_arterielle_soir_systolique', models.IntegerField(validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(200)])),
                ('tension_arterielle_matin_diastolique', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(150)])),
                ('tension_arterielle_soir_diastolique', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(150)])),
                ('symptomes_cardiovasculaires', models.TextField()),
                ('nombre_medicaments_jour', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('oublie_medicament_matin', models.BooleanField(null=True)),
                ('oublie_medicament_soir', models.BooleanField(null=True)),
                ('effets_secondaires', models.BooleanField(null=True)),
                ('symptomes_particuliers', models.BooleanField(null=True)),
                ('description_effets_symptomes', models.TextField()),
                ('consommation_alcool', models.BooleanField(null=True)),
                ('grignotage_sucre', models.BooleanField(null=True)),
                ('grignotage_sale', models.BooleanField(null=True)),
                ('nombre_repas_jour', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('quantite_eau', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('quantite_alcool', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('activite_physique', models.BooleanField(null=True)),
                ('nature_activite_physique', models.CharField(max_length=100, null=True)),
                ('duree_activite_physique', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('presence_dyspnee', models.BooleanField(null=True)),
                ('presence_oedeme', models.BooleanField(null=True)),
                ('presence_episode_infectieux', models.BooleanField(null=True)),
                ('presence_fievre', models.BooleanField(null=True)),
                ('presence_palpitation', models.BooleanField(null=True)),
                ('presence_douleur_thoracique', models.BooleanField(null=True)),
                ('presence_malaise', models.BooleanField(null=True)),
                ('heure_debut_palpitations', models.TimeField(null=True)),
                ('duree_palpitations', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('heure_debut_douleurs_thoraciques', models.TimeField(null=True)),
                ('duree_douleurs_thoraciques', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('heure_debut_malaises', models.TimeField(null=True)),
                ('duree_malaises', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
