# Generated by Django 4.2.5 on 2023-09-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_stressevaluationform_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stressevaluationform',
            name='actions_ou_gestes_impulsifs',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='attaques_verbales_envers_quelquun',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='begaiements_ou_hesitations_verbales',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='besoin_frequent_duriner',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='bouche_seche_ou_gorge_seche',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='cauchemars',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='conflits_significatifs_avec_les_autres',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='debit_plus_rapide',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='diarrhee',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='difficulte_a_dormir_toute_la_nuit_sans_se_reveiller',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='difficulte_a_organiser_ses_pensees',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='difficulte_a_rester_assis',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='difficulte_a_se_lever_apres_le_sommeil',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='difficulte_a_se_remettre_dun_evenement_contrariant',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='difficulte_a_sendormir',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='douleurs_au_dos_ou_a_la_nuque',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='douleurs_ou_serrements_a_la_poitrine',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='fatigue_ou_lourdeur_generalisees',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='geste_ou_sentiment_dimpatience',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='grande_envie_de_faire_mal',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='grande_envie_de_fuir',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='grande_envie_de_pleurer',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='grincement_des_dents',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='hauts_et_bas_emotifs',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='hostilite_envers_les_autres',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='incapacite_ou_difficulte_a_se_concentrer',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='irritabilite',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='mains_moites',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='maux_de_tete',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='maux_destomac_ou_difficultes_a_digerer',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='mouvements_de_retrait_disolement',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='oublis_frequents',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='pensees_embrouillees',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='perte_dinteret_pour_le_sexe',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='perte_ou_gain_dappetit',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='sentiment_danxiete',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='sentiment_de_tristesse',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='sentiment_detre_emotivement_fragile',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='sentiment_detre_surchargé',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='sentiment_que_les_choses_sont_hors_de_controle',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='sentiments_depressifs',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='tension_emotionnelle',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='stressevaluationform',
            name='tremblements_ou_gestes_nerveux',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0),
        ),
    ]
